# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: linux-amd64
      env: 
        GOOS: linux
        GOARCH: amd64
      run: go build -o imgapi-amd64

    - name: linux-arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -o imgapi-arm64

    - name: windows-x64
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -o imgapi.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: |
          imgapi-amd64
          imgapi-arm64
          imgapi.exe

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          imgapi-amd64
          imgapi-arm64
          imgapi.exe
        token: ${{ secrets.GITHUB_TOKEN }}
        release_name: Release ${{ github.event.after }}
